removed the CI check that calls the registry
Signed-off-by: Eddie Knight <knight@linux.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,26 +19,32 @@ jobs:
         with:
           go-version: stable
 
-      - name: Setup Cue
-        uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
-        with:
-          version: v0.15.1
+      # This stopped working with the addition of in-schema conditional validation logic
+      # Leaving as a comment temporarily in hopes that we can come back to this soon
+      # If you see this 30+ days after it's been commented out, please make a PR to remove
 
-      - name: Regenerate types from Gemara spec
-        run: |
-          make generate
-      - name: Check for uncommitted changes
-        run: |
-          if [ -n "$(git status --porcelain)" ]; then
-            echo "Error: Generated types are out of sync with the Gemara specification"
-            echo "The following files have uncommitted changes:"
-            git status --porcelain
-            echo ""
-            echo "Please run 'make generate' locally and commit the changes."
-            exit 1
-          else
-            echo "Generated types are in sync with the Gemara specification"
-          fi
+      # - name: Setup Cue
+      #   uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1
+      #   with:
+      #     version: v0.15.1
+
+      # - name: Regenerate types from Gemara spec
+      #   run: |
+      #     make generate
+
+      # - name: Check for uncommitted changes
+      #   run: |
+      #     if [ -n "$(git status --porcelain)" ]; then
+      #       echo "Error: Generated types are out of sync with the Gemara specification"
+      #       echo "The following files have uncommitted changes:"
+      #       git status --porcelain
+      #       echo ""
+      #       echo "Please run 'make generate' locally and commit the changes."
+      #       exit 1
+      #     else
+      #       echo "Generated types are in sync with the Gemara specification"
+      #     fi
+
       - name: Vet
         run: |
           go vet ./...
